<?php

declare(strict_types=1);

use Hyperf\Database\Seeders\Seeder;
use Hyperf\DbConnection\Db;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $salt = \App\Tools\generateRandomString(8);
        $user = [
            'username' => 'admin',
            'password' => password_hash($salt . '123456', PASSWORD_DEFAULT),
            'email' => '66461682@qq.com',
            'salt' => $salt
        ];

        $db_user = Db::table('user')->insert($user);

        $db_permission = Db::table('permission');
        $data = [
            [
                'id' => 1,
                'name' => '个人资料',
                'code' => 'UserProfile',
                'type' => 'MENU',
                'parentId' => null,
                'path' => '/profile',
                'redirect' => null,
                'icon' => 'i-fe:user',
                'component' => '/src/views/profile/index.vue',
                'layout' => null,
                'keepAlive' => null,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => false,
                'order' => 99,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'name' => '系统管理',
                'code' => 'SysMgt',
                'type' => 'MENU',
                'parentId' => null,
                'path' => null,
                'redirect' => null,
                'icon' => 'i-fe:grid',
                'component' => null,
                'layout' => null,
                'keepAlive' => null,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => true,
                'order' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'name' => '资源管理',
                'code' => 'ResourceMgt',
                'type' => 'MENU',
                'parentId' => 2,
                'path' => "/pms/resource",
                'redirect' => null,
                'icon' => 'i-fe:list',
                'component' => "/src/views/pms/resource/index.vue",
                'layout' => null,
                'keepAlive' => true,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => true,
                'order' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'code' => 'ResourceMenuTree',
                'name' => '权限树-菜单',
                'type' => 'INTERFACE',
                'parentId' => 3,
                'redirect' => null,
                'path' => '/permission/menu/tree',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'GET',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '权限树-菜单',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'code' => 'ResourceMenuAdd',
                'name' => '新增菜单',
                'type' => 'INTERFACE',
                'parentId' => 3,
                'redirect' => null,
                'path' => '/permission',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'POST',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '新增菜单',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'code' => 'ResourceButton',
                'name' => '菜单按钮类型查询接口',
                'type' => 'INTERFACE',
                'parentId' => 3,
                'redirect' => null,
                'path' => '/permission/button',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'GET',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '菜单按钮类型查询接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'code' => 'ResourceMenuEdit',
                'name' => '菜单编辑接口',
                'type' => 'INTERFACE',
                'parentId' => 3,
                'redirect' => null,
                'path' => '/permission',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'PATCH',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '菜单编辑接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'code' => 'ResourceMenuDelete',
                'name' => '菜单删除接口',
                'type' => 'INTERFACE',
                'parentId' => 3,
                'redirect' => null,
                'path' => '/permission',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'DELETE',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '菜单删除接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'name' => '角色管理',
                'code' => 'RoleMgt',
                'type' => 'MENU',
                'parentId' => 2,
                'path' => '/pms/role',
                'redirect' => null,
                'icon' => 'i-fe:user-check',
                'component' => "/src/views/pms/role/index.vue",
                'layout' => null,
                'keepAlive' => true,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => true,
                'order' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'name' => '分配用户',
                'code' => 'RoleUser',
                'type' => 'MENU',
                'parentId' => 9,
                'path' => "/pms/role/user/:roleId",
                'redirect' => null,
                'icon' => "i-fe:user-plus",
                'component' => "/src/views/pms/role/role-user.vue",
                'layout' => 'full',
                'keepAlive' => null,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => false,
                'order' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'code' => 'RoleList',
                'name' => '角色列表接口',
                'type' => 'INTERFACE',
                'parentId' => 9,
                'redirect' => null,
                'path' => '/permission',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'GET',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '角色列表接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'code' => 'RoleEdit',
                'name' => '角色修改接口',
                'type' => 'INTERFACE',
                'parentId' => 9,
                'redirect' => null,
                'path' => '/role',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'PATCH',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '角色修改接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'code' => 'RoleDelete',
                'name' => '角色删除接口',
                'type' => 'INTERFACE',
                'parentId' => 9,
                'redirect' => null,
                'path' => '/role',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'DELETE',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '角色删除接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'code' => 'RoleAdd',
                'name' => '角色新增接口',
                'type' => 'INTERFACE',
                'parentId' => 9,
                'redirect' => null,
                'path' => '/role',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'POST',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '角色新增接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'code' => 'RoleUserAdd',
                'name' => '角色授权接口',
                'type' => 'INTERFACE',
                'parentId' => 9,
                'redirect' => null,
                'path' => '/role/users/add',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'PATCH',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '角色授权接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'code' => 'RoleUserRemove',
                'name' => '角色取消授权接口',
                'type' => 'INTERFACE',
                'parentId' => 9,
                'redirect' => null,
                'path' => '/role/users/remove',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'PATCH',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '角色取消授权接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'name' => '用户管理',
                'code' => 'UserMgt',
                'type' => 'MENU',
                'parentId' => 2,
                'path' => '/pms/user',
                'redirect' => null,
                'icon' => 'i-fe:user',
                'component' => "/src/views/pms/user/index.vue",
                'layout' => null,
                'keepAlive' => true,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => true,
                'order' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'name' => '创建用户',
                'code' => 'AddUser',
                'type' => 'BUTTON',
                'parentId' => 17,
                'path' => null,
                'redirect' => null,
                'icon' => '',
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => null,
                'enable' => true,
                'description' => null,
                'show' => true,
                'order' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'code' => 'UserEdit',
                'name' => '用户修改接口',
                'type' => 'INTERFACE',
                'parentId' => 17,
                'redirect' => null,
                'path' => '/user',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'PATCH',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '用户修改接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'code' => 'UserAdd',
                'name' => '用户新增接口',
                'type' => 'INTERFACE',
                'parentId' => 17,
                'redirect' => null,
                'path' => '/user',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'POST',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '用户新增接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'code' => 'UserDelete',
                'name' => '用户删除接口',
                'type' => 'INTERFACE',
                'parentId' => 17,
                'redirect' => null,
                'path' => '/user',
                'icon' => null,
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'DELETE',
                'order' => 1,
                'enable' => true,
                'show' => false,
                'description' => '用户删除接口',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'code' => 'loginLog',
                'name' => '登录日志',
                'type' => 'MENU',
                'parentId' => 2,
                'redirect' => null,
                'path' => '/system/loginlog',
                'icon' => 'i-fe:file-text',
                'component' => '/src/views/system/login-log/index.vue',
                'layout' => null,
                'keepAlive' => true,
                'method' => null,
                'order' => 55,
                'enable' => true,
                'show' => true,
                'description' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'code' => 'loginLogList',
                'name' => '登录日志列表接口',
                'type' => 'INTERFACE',
                'parentId' => 22,
                'redirect' => null,
                'path' => '/system/loginlog/list',
                'icon' => 'i-fe:file-text',
                'component' => null,
                'layout' => null,
                'keepAlive' => false,
                'method' => 'GET',
                'order' => 55,
                'enable' => true,
                'show' => false,
                'description' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'code' => 'OssManager',
                'name' => '存储管理',
                'type' => 'MENU',
                'parentId' => null,
                'redirect' => null,
                'path' => null,
                'icon' => 'i-fe:hard-drive',
                'component' => '/src/views/system/login-log/index.vue',
                'layout' => null,
                'keepAlive' => null,
                'method' => null,
                'order' => 1,
                'enable' => true,
                'show' => true,
                'description' => null,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
//            [
//                'id' => 24,
//                'code' => 'Tos',
//                'name' => '火山对象存储',
//                'type' => 'MENU',
//                'parentId' => 23,
//                'redirect' => null,
//                'path' => '/oss/tos',
//                'icon' => 'i-fe:cloud',
//                'component' => '/src/views/oss/tos/index.vue',
//                'layout' => null,
//                'keepAlive' => true,
//                'method' => null,
//                'order' => 1,
//                'enable' => true,
//                'show' => true,
//                'description' => null,
//                'created_at' => date('Y-m-d H:i:s'),
//                'updated_at' => date('Y-m-d H:i:s'),
//            ],
//            [
//                'id' => 25,
//                'code' => 'TosList',
//                'name' => '列表数据接口',
//                'type' => 'INTERFACE',
//                'parentId' => 24,
//                'redirect' => null,
//                'path' => '/oss/tos/list',
//                'icon' => null,
//                'component' => null,
//                'layout' => null,
//                'keepAlive' => false,
//                'method' => 'GET',
//                'order' => 1,
//                'enable' => true,
//                'show' => false,
//                'description' => '列表数据接口',
//                'created_at' => date('Y-m-d H:i:s'),
//                'updated_at' => date('Y-m-d H:i:s'),
//            ],
//            [
//                'id' => 26,
//                'code' => 'TosUpload',
//                'name' => '上传接口',
//                'type' => 'INTERFACE',
//                'parentId' => 24,
//                'redirect' => null,
//                'path' => '/oss/tos/upload',
//                'icon' => null,
//                'component' => null,
//                'layout' => null,
//                'keepAlive' => false,
//                'method' => 'POST',
//                'order' => 1,
//                'enable' => true,
//                'show' => false,
//                'description' => '火山存储上传接口',
//                'created_at' => date('Y-m-d H:i:s'),
//                'updated_at' => date('Y-m-d H:i:s'),
//            ],
//            [
//                'id' => 27,
//                'code' => 'TosDelete',
//                'name' => '删除接口',
//                'type' => 'INTERFACE',
//                'parentId' => 24,
//                'redirect' => null,
//                'path' => '/oss/tos',
//                'icon' => null,
//                'component' => null,
//                'layout' => null,
//                'keepAlive' => false,
//                'method' => 'DELETE',
//                'order' => 1,
//                'enable' => true,
//                'show' => false,
//                'description' => '火山存储删除接口',
//                'created_at' => date('Y-m-d H:i:s'),
//                'updated_at' => date('Y-m-d H:i:s'),
//            ],
//            [
//                'id' => 28,
//                'code' => 'TosUpload',
//                'name' => '分享接口',
//                'type' => 'INTERFACE',
//                'parentId' => 24,
//                'redirect' => null,
//                'path' => '/oss/tos/share',
//                'icon' => null,
//                'component' => null,
//                'layout' => null,
//                'keepAlive' => false,
//                'method' => 'GET',
//                'order' => 1,
//                'enable' => true,
//                'show' => false,
//                'description' => '火山存储分享接口',
//                'created_at' => date('Y-m-d H:i:s'),
//                'updated_at' => date('Y-m-d H:i:s'),
//            ],
        ];
        $db_permission->insert($data);


        $db_profile = Db::table('profile');
        $db_profile->insert([
            'id' => 1,
            'address' => null,
            'gender' => 1,
            'avatar' => null,
            'email' => '66461682@qq.com',
            'user_id' => 1,
            'nickName' => '养乐多',
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s')
        ]);

        // 角色初始化
        $db_role = Db::table('role');
        $db_role->insert([
            [
                'id' => 1,
                'code' => 'SUPER_ADMIN',
                'name' => '超级管理员',
                'enable' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'id' => 2,
                'code' => 'test',
                'name' => '测试',
                'enable' => true,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
        ]);
        // 用户权限初始化
        Db::table('user_role')->insert([
            [
                'user_id' => 1,
                'role_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'user_id' => 1,
                'role_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
        ]);
        $db_uer_permission = Db::table('role_permission');
        $db_uer_permission->insert([
            [
                'role_id' => 1,
                'permission_id' => 1,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'role_id' => 1,
                'permission_id' => 2,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'role_id' => 1,
                'permission_id' => 3,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'role_id' => 1,
                'permission_id' => 4,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'role_id' => 2,
                'permission_id' => 1,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'role_id' => 2,
                'permission_id' => 3,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
            [
                'role_id' => 2,
                'permission_id' => 2,
                'created_at' => date('Y-m-d'),
                'updated_at' => date('Y-m-d'),
            ],
        ]);
    }
}
